apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jamespatten1/kalah-web
      context: kalah-web
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/kalah-web-deployment.yaml