apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalah-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: kalah-web
          image: jamespatten1/kalah-web
          env:
            - name: API_HOST
              value: kalah-api-cluster-ip-service
            - name: API_PORT
              value: '8081'
            - name: KEYCLOAK_HOST
              value: keycloak
            - name: KEYCLOAK_PORT
              value: '80'