apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalah-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: kalah-api
          image: jamespatten1/kalah-api
          env:
            - name: KEYCLOAK_HOST
              value: keycloak
            - name: KEYCLOAK_PORT
              value: '80'
          